version: '3.8'
services:
  recipe:
    image: ${DOCKER_REGISTRY-}recipe
    build:
      context: .
      dockerfile: Recipe/Dockerfile
    ports:
      - 44365:80
      - 5401:443 
    #   depends_on:
  #     - sqlserver
  # sqlserver:
  #    image: "mcr.microsoft.com/mssql/server"
     
  #    environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "hackerbt123!@#"
  #    ports:
  #      - 1433:1433
  #    volumes:
  #      - "./data-mssql:/var/opt/mssql"
